local MOD_STRINGS =
{
	KEYBIND =
	{
		HEADER = "MOD - CONTROLLER BINDINGS",
		CONFIRM = "(A) CONFIRM",
		CANCEL = "(B) CANCEL and TURN MENU",
		SELECTPREV = "(LB) PREVIOUS SELECTION",
		SELECTNEXT = "(RB) NEXT SELECTION",
	},
}

return MOD_STRINGS
